modLoader = "javafml" #mandatory
loaderVersion = "${forge_version_range}" #mandatory
license = "${mod_license}" #mandatory

[[mods]] #mandatory
modId = "protectmobsfromdaylight" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory

#updateJSONURL = "https://change.me.example.invalid/updates.json" #optional
# |-> For more information https://docs.minecraftforge.net/en/latest/misc/updatechecker/
#displayURL = "https://change.me.to.your.mods.homepage.example.invalid/" #optional
#logoFile = "forge.png" #optional
#credits = "Thanks for this example mod goes to Java" #optional

authors = "${mod_authors}" #optional
description = "${mod_description}" #optional

[[dependencies.protectmobsfromdaylight]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_version_range}" #mandatory
ordering = "NONE"
side = "SERVER"

[[dependencies.protectmobsfromdaylight]]
modId = "minecraft"
mandatory = true
versionRange = "${forge_mc_version_range}"
ordering = "NONE"
side = "SERVER"
